CREATE TABLE categoria
(
    codigo INTEGER primary key GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(50) not null
);

INSERT INTO categoria (nome) VALUES ('Lazer');
INSERT INTO categoria (nome) VALUES ('Alimentação');
INSERT INTO categoria (nome) VALUES ('Supermercado');
INSERT INTO categoria (nome) VALUES ('Farmácia');
INSERT INTO categoria (nome) VALUES ('Outros');
